jobs:
    check-ci:
        docker:
            - image: cimg/node:16.20.0
        resource_class: small
        steps:
            - checkout
            - run:
                command: |
                    curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
                name: Update circleci
                shell: /bin/bash
            - run:
                command: |
                    npm run circleci:pack
                name: Pack
            - run:
                command: |
                    if [ -n "$(git status --porcelain)" ]; then
                        echo >&2 "Circleci config is not packed!"

                        git diff

                        exit 1
                    fi
                name: Check for changes
                shell: /bin/bash
    init:
        docker:
            - image: cimg/node:16.20.0
        resource_class: small
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - persist_to_workspace:
                paths:
                    - '*'
                root: ./
    step-lint:
        docker:
            - image: cimg/node:16.20.0
        resource_class: small
        steps:
            - attach_workspace:
                at: ./
            - run: yarn run lint
    step-test:
        docker:
            - image: cimg/node:16.20.0
        resource_class: small
        steps:
            - attach_workspace:
                at: ./
            - run: yarn run test -- run --coverage.enabled --coverage.reporter=text --reporter=basic --reporter=junit --outputFile=./reports/junit.xml
            - store_test_results:
                path: ./reports/junit.xml
    step-typecheck:
        docker:
            - image: cimg/node:16.20.0
        resource_class: small
        steps:
            - attach_workspace:
                at: ./
            - run: yarn run typecheck
orbs:
    node: circleci/node@5.1.0
version: 2.1
workflows:
    test:
        jobs:
            - check-ci
            - init
            - step-lint:
                requires:
                    - init
            - step-test:
                requires:
                    - init
            - step-typecheck:
                requires:
                    - init

