docker:
  - image: cimg/node:16.20.0
resource_class: small

steps:
  - checkout
  # We need this step because the circleci CLI is not installed inside their images.
  - run:
      shell: /bin/bash
      name: Update circleci
      command: |
        curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | bash
  - run:
      name: Pack
      command: |
        npm run circleci:pack
  - run:
      name: Check for changes
      shell: /bin/bash
      command: |
        if [ -n "$(git status --porcelain)" ]; then
            echo >&2 "Circleci config is not packed!"

            git diff

            exit 1
        fi
